version: '3'

services: 
  mongodb:
    build: ./mongodb
    hostname: mongodb
    # restart: unless-stopped
    ports:
    - "${MONGODB_PORT}:27017"
    volumes:
      - ./data/mongodb:/data/db
    env_file:
      - ./mongodb.env